# NumPy
Numpy es una librearia de Algebra Lineal para Python, la razon por la que es importante para Data Science con Python es que casi todas las librerias en el Ecosistema de Pydata recaen en Numpy como uno  de sus bloques fuentes principales

Numpy es tambien increiblemente rapido, tiene uniones con librerias de C. La mayoria prefiere utilizar Arrays de Numpy en vez de listas.

## Instrucciones de instalación
Abrir el CMD y tipear la siguiente linea:
    conda install numpy
    


## Usando Numpy

In [1]:
import numpy as np

## Numpy Arrays

Numpy Arrays son la forma principal en la que se usara Numpy atraves del curso. Los arreglos Numpy vienen de 2 formas: Vectores y Matrices.

#### Vectores son estrictamente unidimensionales
#### Matrices son de 2 dimensiones, aunque pueda ser que veas que solo tenga 1 columna o 1 fila

## Creando Arreglos Numpy
### De una lista de Python
Podemos crear un array si convertimos directamente una lista o una lista de listas


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Metodos incluidos
Hay un monton de metodos incluidos para generar arrays

### arange
Retorna valores en un intervalo separados equitativamente

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros y ones
Genera arrays de ceros o unos

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna numeros separados equitativamente sobre un intervalo especificado

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

### eye
Retorna una matriz de identidad

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random
Numpy tambien tiene una funcion para crear arreglos de numeros aleatorios:

### rand
Crea un array dado una forma y lo rellena de numeros aleatorios de una distribucion uniforme entre [0,1])

In [15]:
np.random.rand(2)

array([ 0.68406495,  0.07940313])

In [16]:
np.random.rand(5,5)

array([[ 0.85871689,  0.6812514 ,  0.35604155,  0.98899888,  0.10490922],
       [ 0.00347495,  0.11889092,  0.35706389,  0.92039452,  0.61278617],
       [ 0.48525656,  0.96923356,  0.67381068,  0.36719236,  0.47589982],
       [ 0.00438596,  0.3192639 ,  0.66182062,  0.18206439,  0.3974896 ],
       [ 0.92038811,  0.15125881,  0.85037794,  0.81369886,  0.37897837]])

### randn
Crea un array de numeros aleatorios de una distribucion "estandar":

In [17]:
np.random.randn(2)

array([ 0.88018118, -0.4074237 ])

In [18]:
np.random.randn(5,5)

array([[-0.41149506, -0.1993911 , -0.54805187,  0.79767742,  0.56266429],
       [-0.1504757 ,  1.16619137,  0.03497962, -2.24980719, -0.33768181],
       [ 1.43591177, -2.44960492, -0.19508419,  0.08415355, -0.16246071],
       [-0.34076802, -0.70966231,  0.90745956, -1.32423396,  0.81414397],
       [ 0.35893605, -0.17387084,  0.54327611, -1.06646371,  1.71043725]])

### randint
Crea un array de valores enteros entre 2 valores dados.

In [19]:
np.random.randint(1,100)

41

In [20]:
np.random.randint(1,100,10)

array([98, 63, 80, 57, 26, 94, 23, 59, 17, 46])

## Metodos y Atributos de los Arrays
Veamos algunos metodos y atributos utiles de un array:

In [3]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
ranarr

array([46, 35, 21, 12, 23, 41, 24, 41, 45,  6])

### Reshape
Retorna un array conteniendo al misma data con una neuva forma

In [6]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
arr2=np.arange(23)

In [8]:
arr2.reshape(5,5)

ValueError: cannot reshape array of size 23 into shape (5,5)

### max,min,argmax,argmin
Estos metodos nos permites encontrar el valor maximo y minimo, asi como ubicar el indice donde se encuentra el maximo y minimo utilizando argmin o argmax

In [26]:
ranarr

array([ 9,  3, 11, 24, 19, 31, 46,  1, 27,  7])

In [27]:
ranarr.max()

46

In [28]:
ranarr.argmax()

6

In [29]:
ranarr.min()

1

In [30]:
ranarr.argmin()

7

### Shape 
Shape es un atributo de un array que nos devuelve el tamaño de un array

In [9]:
#Vector
arr.shape

(25,)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
#Notece el orden de las variables en el parentesis
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [12]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Tambien se puede ver el tipo de dato que es el objeto array

In [36]:
arr.dtype

dtype('int32')

# Operaciones con Numpy
## Aritmeticas
Uno puede facilmente realizar operacion entre arrays - arrays o escalar-arrays

In [13]:
import numpy as np
arr=np.arange(0,10)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
#Alerta al dividir por zero, pero no genera error, es solo una advertencia
arr/arr

C:\Users\usuario 24\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
#Tambien genera advertencia 
1.0/arr

C:\Users\usuario 24\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr.dtype

dtype('int32')

In [23]:
np.uint8(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [27]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [28]:
np.uint8(arr**3)

array([  0,   1,   8,  27,  64, 125, 216,  87,   0, 217], dtype=uint8)

# Funciones universales con arrays
Numpy viene con muchas funciones universales, que son esencialmente operaciones matematicas que se puede usar con los arrays, repasemos algunas.

In [29]:
#Raiz cuadrada
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [30]:
#Calculo exponencial
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
#Obtencion de valores maximos
np.max(arr)

9

In [31]:
#Operacioens trigonometricas
np.sin(np.pi*arr)

array([ 0.00000000e+00,  1.22464680e-16, -2.44929360e-16,  3.67394040e-16,
       -4.89858720e-16,  6.12323400e-16, -7.34788079e-16,  8.57252759e-16,
       -9.79717439e-16,  1.10218212e-15])

In [32]:
#Operaciones logaritmicas
np.log(arr)

C:\Users\usuario 24\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Indexing y seleccion en Numpy


In [54]:

arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
#A diferencia de las listas en Python se puede alterar varios valores
#Con el indexado
arr[0:5]=100

In [57]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
mini=arr[0:6]

In [48]:
mini

array([0, 1, 2, 3, 4, 5])

In [49]:
mini[:]=99

In [50]:
mini

array([99, 99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

La data no es copiada, es sobreescrita del array original, esto lo hace para evitar problemas de memoria.

In [59]:
arr_copy=arr.copy()

In [61]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr_copy[0:6]=99

In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr=None

## Indexado de arrays de 2D (Matrices)
El formato general de una matriz es arr_2d[row][col] o arr_2d[row,col]

In [68]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
#Indexacion de fila
arr_2d[1]

array([20, 25, 30])

In [71]:
arr_2d[1][0]

20

In [72]:
arr_2d[0][0]

5

In [73]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
#Slicing de array 2D
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
#Obtencion de la ultima fila
arr_2d[2,:]

array([35, 40, 45])

In [77]:
arr_2d[:,2]

array([15, 30, 45])

## Indexado rapido
Este metodo permite seleccionar con facilidad la filas o columnas  sin importar el orden

In [86]:
arr2d = np.zeros((10,10))

In [87]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
arr_length = arr2d.shape[1]
arr_length

10

In [89]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [90]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [91]:
var1=arr2d[[6,4,2,7]]

In [94]:
var1.shape

(4, 10)

In [95]:
var1

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Seleccion

In [96]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [97]:
bool_arr = arr>4

In [98]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [99]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

image searching NumPy indexing

# Ejercicios

In [103]:
a=[[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]]

In [104]:
a

[[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1],
 [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2],
 [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3],
 [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4],
 [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5],
 [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6],
 [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7],
 [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8],
 [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9],
 [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]]

In [105]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [107]:
np.linspace(1,100,100).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [111]:
np.linspace(0.1,1,100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

In [112]:
mat = np.arange(1,26).reshape(5,5)

In [113]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
[[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]]

[[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]

In [116]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [117]:
[[ 2],
       [ 7],
       [12]]

[[2], [7], [12]]

In [119]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [120]:
#Hacer una funcion que genere 2 array de 6 elementos cada uno,
#con valores enteros entre 0 1
#Y que retorne True o False si es que ambos son iguales
#Ejemplo> [0 1 0 0 1 1] y [1 1 1 0 0 1]


In [145]:
def comparador():
    
    x=np.random.randint(0,2,6)
    print(x)
    y=np.random.randint(0,2,6)
    print(y)
    #return np.array_equal(x,y)
    a= ( x==y)
    return(a.all())

In [171]:
comparador()

[0 1 0 1 0 1]
[0 1 1 1 1 0]


False